app/gm/config/routes.rb
Gm::Application.routes.draw do

  get "limit_event/list"
  get "limit_event/edit"
  get "limit_event/new"
  get "limit_event/delete"
  post "limit_event/create"
  post "limit_event/update"

  get "normal_event/list"
  get "normal_event/edit"
  get "normal_event/new"
  get "normal_event/delete"
  post "normal_event/create"
  post "normal_event/update"

  get "events_campaign_exp/list"

  get "cdkeys/index"
  get "cdkeys/search"
  get "cdkeys/manage"
  post "cdkeys/generate"
  post "cdkeys/process_redeemed_cdkeys"
  post "cdkeys/import_from_local"
  post "cdkeys/import"
  post "cdkeys/export_all"

  get "cdkey/index"

  root :to => "application#index"

  match "i18n" => 'application#i18n', :via => :put
  match "logout" => 'user_sessions#destroy', :via => :get

  post 'api/client_version'
  post 'api/maintainance'
  post 'api/list_zones'
  post 'api/list_user_zones'
  post 'api/is_valid_cdkey'
  post 'api/use_cdkey'
  post 'api/list_user_zones'
  post "api/get_game_characters"
  post 'api/process_action_log'
  post 'api/process_redeemed_cdkeys'

  get 'site_users/list'
  match 'site_users/:id/update_super' => 'site_users#update_super', :via => :put
  match 'site_users/:id/update_role' => 'site_users#update_role', :via => :put
  match 'site_users/:id/update_active' => 'site_users#update_active', :via => :put
  match 'site_users/:id/reset_failed_login_count' => 'site_users#reset_failed_login_count', :via => :post
  match 'site_users/:id/edit_role' => 'site_users#edit_role', :via => :get, :as => :edit_site_user_role
  match 'site_users/:id/edit_active' => 'site_users#edit_active', :via => :get, :as => :edit_site_user_active
  match 'site_users/:id/edit_super(.:format)' => 'site_users#edit_super', :via => :get, :as => :edit_site_user_super
  match 'site_users/:id/deliver_verification_instructions' => 'site_users#deliver_verification_instructions', :via => :post, :as => :deliver_verification_instructions
  match 'site_users/:id/skip_verification' => 'site_users#skip_verification', :via => :post, :as => :skip_verification
  match 'site_user_verification/:token' => 'site_user_verification#show', :via => :get, :as => :site_user_verification
  get 'site_user_records/index'
  get 'site_user_records/search'

  get 'notif_alerts/list', :as => :list_notif_alerts
  post 'notif_alerts/check_all' => 'notif_alerts#check_all', :as => :check_notif_alert_all
  match 'notif_alerts/:id/edit' => 'notif_alerts#edit', :via => :get, :as => :edit_notif_alert
  post 'notif_alerts/:id/check' => 'notif_alerts#check', :as => :check_notif_alert

  get 'notif_receivers/list', :as => :list_notif_receivers
  match 'notif_receivers/:id/edit' => 'notif_receivers#edit', :via => :get, :as => :edit_notif_receiver

  match 'grant_records/grant'  => 'grant_records#grant', :via => :post
  match 'grant_records/reject' => 'grant_records#reject', :via => :post
  match 'grant_records/old_requests' => 'grant_records#old_requests', :via => :get
  resources :grant_records

  get 'wldh/list'
  match 'wldh/:id/stages/:stage' => 'wldh#show_stages', :via => :get, :as => :stages_wldh
  match 'wldh/:id/stages/:stage/:zone/:player_id' => 'wldh#show_stages_player', :via => :get, :as => :stages_player_wldh
  match 'wldh/:id/stages/:stage/fights/:mode/:fight_id' => 'wldh#show_stages_fight', :via => :get, :as => :stages_fight_wldh
  match 'wldh/:id/activate' => 'wldh#activate', :via => :post, :as => :activate_wldh
  match 'wldh/:id/boost' => 'wldh#boost', :via => :post, :as => :boost_wldh
  match 'wldh/:id/enroll' => 'wldh#enroll', :via => :post, :as => :enroll_wldh
  match 'wldh/:id/reset_stages' => 'wldh#reset_stages', :via => :post, :as => :reset_wldh_stages
  match 'wldh/grant/:id/:grant' => 'wldh#grant', :via => :post, :as => :grant_wldh
  match 'wldh/viewWulinRanks' => 'wldh#viewWulinRanks', :via => :get

  get 'data_query/index'
  post 'data_query/cache'
  post 'data_query/debug'
  post 'data_query/submit'
  match 'data_query/log/:id' => 'data_query#showlog', :via => :get
  match 'data_query/log/:id' => 'data_query#deletelog', :via => :delete

  match 'cdkey/queryKey/:key' => 'cdkey#queryKey', :via => :get

  resources :user_sessions
  resources :site_users
  resources :site_user_records
  resources :notif_alerts
  resources :notif_receivers
  resources :wldh

  get 'client_version/index'
  get 'client_version/edit'
  post 'client_version/publish'

  get 'app_version/index'
  get 'app_version/edit'
  post 'app_version/publish'

  get 'zone/index'
  post 'zone/saveNumOpenZones'

  get 'maintainance/index'
  post 'maintainance/update'

  get 'gm_pay/index'
  post 'gm_pay/add'

  get 'server_settings/index'
  post 'server_settings/dev_mode'
  post 'server_settings/save'
  post 'server_settings/delete'
  post 'server_settings/reload_server_list'
  post 'server_settings/garbage_collect_all'

  get 'zone_settings/index'
  post 'zone_settings/save'
  post 'zone_settings/open_zone_auto_set'
  post 'zone_settings/restore_default_settings'
  post 'zone_settings/delete'

  get 'queuing_settings/index'
  post 'queuing_settings/save'
  post 'queuing_settings/delete'

  get "bills/index"
  get "bills/search"
  get 'bills/total'
  get 'bills/low_search'

  get 'data/view'
  get 'data/player'
  get 'data/give'
  get "/data/query_guild"
  post "/data/guild_search"
  
  get 'editdata/edit'

  match 'actionlog' => 'data#actionlog', :via => :get
  match 'actionlogSpecial' => 'data#actionlogSpecial', :via => :get

  get "wushuplayer/raw"
  get "wushuplayer/load"

  get "action_logs/index"
  get "action_logs/search"
  get "action_logs/manage"
  post "action_logs/delete_old"
  post "action_logs/process_remain_logs"

  get "elastic_action_log/index"
  get "elastic_action_log/search"

  get "anti_cheat/index"
  get "anti_cheat/search_cheater", :as => :search_cheater
  post "anti_cheat/add_cheater", :as => :add_cheater
  post "anti_cheat/del_cheater", :as => :del_cheater
  post "anti_cheat/clear_cheaters", :as => :clear_cheaters
  get "anti_cheat/search_monitor", :as => :search_monitor
  post "anti_cheat/add_monitor", :as => :add_monitor
  post "anti_cheat/del_monitor", :as => :del_monitor
  post "anti_cheat/clear_monitors", :as => :clear_monitors

  match 'archive/:zone/:id' => 'archive#find', :via => :get, :as => :archive_find
  match 'archive/:zone/:id/:time' => 'archive#load', :via => :get, :as => :archive_view
  match 'archive/:zone/:id/:time/delete' => 'archive#delete', :via => :post, :as => :archive_delete

  get 'config/complete/:type' => 'config#complete'

  match 'archive/:zone/:id' => 'archive#find', :via => :get, :as => :archive_find
  match 'archive/:zone/:id/:time' => 'archive#load', :via => :get, :as => :archive_view
  match 'archive/:zone/:id/:time/delete' => 'archive#delete', :via => :post, :as => :archive_delete

  get 'data/view'
  get 'data/history'
  get 'data/raw'
  get 'data/give'
  get 'data_batch/edit'
  post 'data_batch/save'
  post 'data_batch/batch_save'

  match 'data/:zone/:id' => 'data#load', :via => :get
  match 'data/:zone/:id/json' => 'data#export', :via => :get
  match 'data/:zone/:id/json' => 'data#import', :via => :put
  match 'data/:zone/:id' => 'data#save', :via => :put
  match 'data/:zone/:id' => 'data#delete', :via => :delete

  post "player/set_permission"
  post "player/permission_list"
  post "player/get_permission"
  post "player/get_block_detail"
  post "player/unlock_block"
  post "player/set_player_permission"
  get "player/index"
  match "player/:zone/:name" => 'player#byName', :via => :get
  match "player/kick/:zone/:id" => 'player#kick', :via => :post

  get "user/index"
  post "user/query"
  post "user/query_player"
  match "user/by_email" => 'guser#by_email', :via => :get
  match "user/:id" => 'guser#by_id', :via => :get

  match 'permissions' => 'permissions#show', :via => :get
  match 'permissions/create' => 'permissions#create', :via => :post, :as => :permissions_create
  match 'permissions/update' => 'permissions#update', :via => :post, :as => :permissions_update
  match 'permissions/delete' => 'permissions#destroy', :via => :post, :as => :permissions_delete
  match 'permissions/sort' => 'permissions#sort', :via => :post, :as => :permissions_sort

  get "channel/index"
  post "channel/notice"
  post "channel/chat"
  post "channel/add_chat_schedule"
  post "channel/remove_chat_schedule"

  get "sms/index"

  get "events_zhaoxian/index"
  get "events_zhaoxian/list"
  get "events_zhaoxian/new"
  get "events_zhaoxian/edit"
  post 'events_zhaoxian/create_zhaoxian'
  post 'events_zhaoxian/update'
  match "events_zhaoxian/delete" => 'events_zhaoxian#delete_zhaoxian', :via => :post
  post "events_zhaoxian/delete_zhaoxian"
  match 'events_zhaoxian/copy/:zone/:id/' => 'events_zhaoxian#copy', :via => :post
  match 'events_zhaoxian/:zone/copy_list' => 'events_zhaoxian#copy_list', :via => :post

  get "events_campaign_exp/index"
  get "events_campaign_exp/list"
  get "events_campaign_exp/new"
  get "events_campaign_exp/edit"
  post 'events_campaign_exp/create_campaign_exp'
  post 'events_campaign_exp/update'
  match "events_campaign_exp/delete" => 'events_campaign_exp#delete_campaign_exp', :via => :post
  post "events_campaign_exp/delete_campaign_exp"
  match 'events_campaign_exp/copy/:zone/:id/' => 'events_campaign_exp#copy', :via => :post
  match 'events_campaign_exp/:zone/copy_list' => 'events_campaign_exp#copy_list', :via => :post

  get "events_zonemarket/index"
  get "events_zonemarket/list"
  get "events_zonemarket/new"
  get "events_zonemarket/edit"
  post 'events_zonemarket/create_zonemarket'
  post 'events_zonemarket/update'
  match "events_zonemarket/delete" => 'events_zonemarket#delete_zonemarket', :via => :post
  post "events_zonemarket/delete_zonemarket"
  match 'events_zonemarket/copy/:zone/:id/' => 'events_zonemarket#copy', :via => :post
  match 'events_zonemarket/:zone/copy_list' => 'events_zonemarket#copy_list', :via => :post

  get "events_soul/index"
  get 'events_soul/list'

app/gm/app/models/site_user_record.rb
# encoding: utf-8

class SiteUserRecord < ActiveRecord::Base

  attr_accessible :action, :success, :target, :zone, :tid, :count, :param1, :param2, :param3

  belongs_to :site_user

  self.per_page = 100

  def self.search(site_user_id, a, target, zone, tid,
    created_at_s, created_at_e, sort, direction, page, per_page)

    sort = (not sort.nil? or SiteUserRecord.column_names.include? sort) ? sort : 'created_at'
    direction = (direction.nil? or direction.downcase == 'desc') ? 'desc' : 'asc'
    page = 1 if page.to_i == 0
    per_page = self.per_page if per_page.to_i == 0

    queries = []
    fields = {}
    unless site_user_id.blank?
      queries << 'site_user_id = :site_user_id'
      fields[:site_user_id] = site_user_id
    end
    unless a.blank?
      queries << 'action = :action'
      fields[:action] = a
    end
    unless target.blank?
      queries << 'target = :target'
      fields[:target] = target
    end
    unless zone.blank?
      queries << 'zone = :zone'
      fields[:zone] = zone
    end
    unless tid.blank?
      queries << 'tid = :tid'
      fields[:tid] = tid
    end
    unless created_at_s.blank?
      queries << 'created_at >= :created_at_s'
      fields[:created_at_s] = TimeHelper.parse_date_time(created_at_s)
    end
    unless created_at_e.blank?
      queries << 'created_at <= :created_at_e'
      fields[:created_at_e] = TimeHelper.parse_date_time(created_at_e)
    end

    where(queries.join(' AND '), fields)
    .order("#{sort} #{direction}")
    .paginate(:page => page, :per_page => per_page)
  end

end

app/gm/app/controllers/site_user_records_controller.rb
class SiteUserRecordsController < ApplicationController

  include RsRails

  layout 'main'

  protect_from_forgery

  before_filter :require_user

  access_control do
    allow :admin
    allow :p0, :p1 => [:index, :search]
  end

  def index
    sort = params[:sort]
    direction = params[:direction]
    sort = (not sort.nil? or SiteUserRecord.column_names.include? sort) ? sort : 'created_at'
    direction = (direction.nil? or direction.downcase == 'desc') ? 'desc' : 'asc'

    @records = SiteUserRecord.order("#{sort} #{direction}")
      .paginate(:page => params[:page], :per_page => params[:per_page])

    render :search
  end

  def new
    @record = SiteUserRecord.new
  end

  def create
    @record = SiteUserRecord.new(params[:record])
    @record.save
  end

  def show
    @record = SiteUserRecord.find(params[:id])
  end

  def edit
    @record = SiteUserRecord.find(params[:id])
  end

  def update
    @record = SiteUserRecord.find(params[:id])
    if @record.update_attributes(params[:record])
      flash[:notice] = "SiteUserRecord updated!"
      redirect_to edit_record_url(@user)
    else
      flash[:error] = "SiteUserRecord updated failed!"
      render :action => :edit
    end
  end

  def search
    if params[:site_user_name]
      params[:site_user_id] = SiteUser.find_by_username_or_email(params[:site_user_name])
    end

    @records = SiteUserRecord.search(
      params[:site_user_id],
      params[:a],
      params[:target],
      params[:zone],
      params[:tid],
      params[:created_at_s],
      params[:created_at_e],
      params[:sort],
      params[:direction],
      params[:page],
      params[:per_page],
      )
  end

end

app/gm/app/helpers/site_user_records_helper.rb
module SiteUserRecordsHelper

  def sortable(column, params, title = nil)
    sort = params[:sort]
    direction = params[:direction]

    title ||= column.titleize
    direction = column == sort && direction == "desc" ? "asc" : "desc"
    css_class = column == sort ? "current #{direction}" : nil

    params_new = params.clone
    params_new[:sort] = column
    params_new[:direction] = direction
    link_to title, params_new, {:class => css_class}
  end

  def unsortable(column, params, title = nil)
    title ||= column.titleize
  end

end

app/gm/app/views/site_user_records/search.html.erb
<style>
.success { color: green; }
.fail { color: red; }
</style>

<%= form_tag site_user_records_search_url, :method => 'get' do %>
  <div class="row">
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon"><%= t(:username) %></span>
        <%= text_field_tag :site_user_name, params[:site_user_name], :class => "form-control" %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon"><%= t(:record_type) %></span>
        <%= text_field_tag :a, params[:a], :class => "form-control" %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon"><%= t(:target_player_id) %></span>
        <%= text_field_tag :target, params[:target], :class => "form-control" %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon"><%= t(:zone) %></span>
        <%= text_field_tag :zone, params[:zone], :class => "form-control" %>
      </div>
    </div>
  </div>

  <br/>

  <div class="row">
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon"><%= t(:goods_type_id) %></span>
        <%= text_field_tag :tid, params[:tid], :class => "form-control" %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon"><%= t(:created_at) %></span>
        <%= text_field_tag :created_at_s, params[:created_at_s], :class => "form-control" %>
      </div>
    </div>
    <div class="col-md-3">
      <%= text_field_tag :created_at_e, params[:created_at_e], :class => "form-control" %>
    </div>
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-addon"><%= t(:num_per_page) %></span>
        <%= text_field_tag :per_page, params[:per_page], :class => "form-control" %>
      </div>
    </div>
  </div>

  <br/>

  <div class="row">
    <div class="col-md-2">
      <%= submit_tag t(:search), :class => "btn btn-info" %>
    </div>
  </div>
<% end %>

<br/>

<table class='table table-striped table-bordered table-hover'>

  <col />
  <col />
  <col />
  <col />
  <col />
  <col />
  <col />
  <col />
  <col />
  <col />
  <col />

  <tr>
    <th><%= sortable "site_user_id", params %></th>
    <th><%= sortable "action", params %></th>
    <th><%= sortable "success", params %></th>
    <th><%= sortable "target", params %></th>
    <th><%= sortable "zone", params %></th>
    <th><%= sortable "type", params %></th>
    <th><%= sortable "count", params %></th>
    <th><%= sortable "param1", params %></th>
    <th><%= sortable "param2", params %></th>
    <th><%= sortable "param3", params %></th>
    <th><%= sortable "created_at", params %></th>
  </tr>

  <% for record in @records %>
  <tr>
    <% user = SiteUser.find(record.site_user_id) %>
    <td><%= link_to user.username, site_user_url(record.site_user_id) %></td>
    <td><%= record.action %></td>
    <td>
      <% if record.success == true %>
        <span class='success'><%= t(:success) %></span>
      <% else %>
        <span class='fail'><%= t(:fail) %></span>
      <% end %>
    </td>
    <td>
      <% if record.target and record.target.length %>
        <%= link_to record.target, data_raw_url( :id => record.target, :zone => record.zone ) %></td>
      <% end %>
    <td>
      <% if record.zone %>
        <%= "#{record.zone}" %>
      <% else %>
      <% end %>
    </td>
    <td><%= record.tid %></td>
    <td><%= record.count %></td>
    <td><%= record.param1 %></td>
    <td><%= record.param2 %></td>
    <td><%= record.param3 %></td>
    <td><%= TimeHelper.gen_date_time_sec(record.created_at) %></td>
  </tr>
  <% end %>

</table>

<div>
<%= will_paginate @records %>
</div>

<script type='text/javascript'>
  $('#created_at_s').datetimepicker();
  $('#created_at_e').datetimepicker();
</script>