app/gm/config/routes.rb
Gm::Application.routes.draw do

  get "limit_event/list"
  get "limit_event/edit"
  get "limit_event/new"
  get "limit_event/delete"
  post "limit_event/create"
  post "limit_event/update"

  get "normal_event/list"
  get "normal_event/edit"
  get "normal_event/new"
  get "normal_event/delete"
  post "normal_event/create"
  post "normal_event/update"

  get "events_campaign_exp/list"

  get "cdkeys/index"
  get "cdkeys/search"
  get "cdkeys/manage"
  post "cdkeys/generate"
  post "cdkeys/process_redeemed_cdkeys"
  post "cdkeys/import_from_local"
  post "cdkeys/import"
  post "cdkeys/export_all"

  get "cdkey/index"

  root :to => "application#index"

  match "i18n" => 'application#i18n', :via => :put
  match "logout" => 'user_sessions#destroy', :via => :get

  post 'api/client_version'
  post 'api/maintainance'
  post 'api/list_zones'
  post 'api/list_user_zones'
  post 'api/is_valid_cdkey'
  post 'api/use_cdkey'
  post 'api/list_user_zones'
  post "api/get_game_characters"
  post 'api/process_action_log'
  post 'api/process_redeemed_cdkeys'

  get 'site_users/list'
  match 'site_users/:id/update_super' => 'site_users#update_super', :via => :put
  match 'site_users/:id/update_role' => 'site_users#update_role', :via => :put
  match 'site_users/:id/update_active' => 'site_users#update_active', :via => :put
  match 'site_users/:id/reset_failed_login_count' => 'site_users#reset_failed_login_count', :via => :post
  match 'site_users/:id/edit_role' => 'site_users#edit_role', :via => :get, :as => :edit_site_user_role
  match 'site_users/:id/edit_active' => 'site_users#edit_active', :via => :get, :as => :edit_site_user_active
  match 'site_users/:id/edit_super(.:format)' => 'site_users#edit_super', :via => :get, :as => :edit_site_user_super
  match 'site_users/:id/deliver_verification_instructions' => 'site_users#deliver_verification_instructions', :via => :post, :as => :deliver_verification_instructions
  match 'site_users/:id/skip_verification' => 'site_users#skip_verification', :via => :post, :as => :skip_verification
  match 'site_user_verification/:token' => 'site_user_verification#show', :via => :get, :as => :site_user_verification
  get 'site_user_records/index'
  get 'site_user_records/search'

  get 'notif_alerts/list', :as => :list_notif_alerts
  post 'notif_alerts/check_all' => 'notif_alerts#check_all', :as => :check_notif_alert_all
  match 'notif_alerts/:id/edit' => 'notif_alerts#edit', :via => :get, :as => :edit_notif_alert
  post 'notif_alerts/:id/check' => 'notif_alerts#check', :as => :check_notif_alert

  get 'notif_receivers/list', :as => :list_notif_receivers
  match 'notif_receivers/:id/edit' => 'notif_receivers#edit', :via => :get, :as => :edit_notif_receiver

  match 'grant_records/grant'  => 'grant_records#grant', :via => :post
  match 'grant_records/reject' => 'grant_records#reject', :via => :post
  match 'grant_records/old_requests' => 'grant_records#old_requests', :via => :get
  resources :grant_records

  get 'wldh/list'
  match 'wldh/:id/stages/:stage' => 'wldh#show_stages', :via => :get, :as => :stages_wldh
  match 'wldh/:id/stages/:stage/:zone/:player_id' => 'wldh#show_stages_player', :via => :get, :as => :stages_player_wldh
  match 'wldh/:id/stages/:stage/fights/:mode/:fight_id' => 'wldh#show_stages_fight', :via => :get, :as => :stages_fight_wldh
  match 'wldh/:id/activate' => 'wldh#activate', :via => :post, :as => :activate_wldh
  match 'wldh/:id/boost' => 'wldh#boost', :via => :post, :as => :boost_wldh
  match 'wldh/:id/enroll' => 'wldh#enroll', :via => :post, :as => :enroll_wldh
  match 'wldh/:id/reset_stages' => 'wldh#reset_stages', :via => :post, :as => :reset_wldh_stages
  match 'wldh/grant/:id/:grant' => 'wldh#grant', :via => :post, :as => :grant_wldh
  match 'wldh/viewWulinRanks' => 'wldh#viewWulinRanks', :via => :get

  get 'data_query/index'
  post 'data_query/cache'
  post 'data_query/debug'
  post 'data_query/submit'
  match 'data_query/log/:id' => 'data_query#showlog', :via => :get
  match 'data_query/log/:id' => 'data_query#deletelog', :via => :delete

  match 'cdkey/queryKey/:key' => 'cdkey#queryKey', :via => :get

  resources :user_sessions
  resources :site_users
  resources :site_user_records
  resources :notif_alerts
  resources :notif_receivers
  resources :wldh

  get 'client_version/index'
  get 'client_version/edit'
  post 'client_version/publish'

  get 'app_version/index'
  get 'app_version/edit'
  post 'app_version/publish'

  get 'zone/index'
  post 'zone/saveNumOpenZones'

  get 'maintainance/index'
  post 'maintainance/update'

  get 'gm_pay/index'
  post 'gm_pay/add'

  get 'server_settings/index'
  post 'server_settings/dev_mode'
  post 'server_settings/save'
  post 'server_settings/delete'
  post 'server_settings/reload_server_list'
  post 'server_settings/garbage_collect_all'

  get 'zone_settings/index'
  post 'zone_settings/save'
  post 'zone_settings/open_zone_auto_set'
  post 'zone_settings/restore_default_settings'
  post 'zone_settings/delete'

  get 'queuing_settings/index'
  post 'queuing_settings/save'
  post 'queuing_settings/delete'

  get "bills/index"
  get "bills/search"
  get 'bills/total'
  get 'bills/low_search'

  get 'data/view'
  get 'data/player'
  get 'data/give'
  get "/data/query_guild"
  post "/data/guild_search"
  
  get 'editdata/edit'

  match 'actionlog' => 'data#actionlog', :via => :get
  match 'actionlogSpecial' => 'data#actionlogSpecial', :via => :get

  get "wushuplayer/raw"
  get "wushuplayer/load"

  get "action_logs/index"
  get "action_logs/search"
  get "action_logs/manage"
  post "action_logs/delete_old"
  post "action_logs/process_remain_logs"

  get "elastic_action_log/index"
  get "elastic_action_log/search"

  get "anti_cheat/index"
  get "anti_cheat/search_cheater", :as => :search_cheater
  post "anti_cheat/add_cheater", :as => :add_cheater
  post "anti_cheat/del_cheater", :as => :del_cheater
  post "anti_cheat/clear_cheaters", :as => :clear_cheaters
  get "anti_cheat/search_monitor", :as => :search_monitor
  post "anti_cheat/add_monitor", :as => :add_monitor
  post "anti_cheat/del_monitor", :as => :del_monitor
  post "anti_cheat/clear_monitors", :as => :clear_monitors

  match 'archive/:zone/:id' => 'archive#find', :via => :get, :as => :archive_find
  match 'archive/:zone/:id/:time' => 'archive#load', :via => :get, :as => :archive_view
  match 'archive/:zone/:id/:time/delete' => 'archive#delete', :via => :post, :as => :archive_delete

  get 'config/complete/:type' => 'config#complete'

  match 'archive/:zone/:id' => 'archive#find', :via => :get, :as => :archive_find
  match 'archive/:zone/:id/:time' => 'archive#load', :via => :get, :as => :archive_view
  match 'archive/:zone/:id/:time/delete' => 'archive#delete', :via => :post, :as => :archive_delete

  get 'data/view'
  get 'data/history'
  get 'data/raw'
  get 'data/give'
  get 'data_batch/edit'
  post 'data_batch/save'
  post 'data_batch/batch_save'

  match 'data/:zone/:id' => 'data#load', :via => :get
  match 'data/:zone/:id/json' => 'data#export', :via => :get
  match 'data/:zone/:id/json' => 'data#import', :via => :put
  match 'data/:zone/:id' => 'data#save', :via => :put
  match 'data/:zone/:id' => 'data#delete', :via => :delete

  post "player/set_permission"
  post "player/permission_list"
  post "player/get_permission"
  post "player/get_block_detail"
  post "player/unlock_block"
  post "player/set_player_permission"
  get "player/index"
  match "player/:zone/:name" => 'player#byName', :via => :get
  match "player/kick/:zone/:id" => 'player#kick', :via => :post

  get "user/index"
  post "user/query"
  post "user/query_player"
  match "user/by_email" => 'guser#by_email', :via => :get
  match "user/:id" => 'guser#by_id', :via => :get

  match 'permissions' => 'permissions#show', :via => :get
  match 'permissions/create' => 'permissions#create', :via => :post, :as => :permissions_create
  match 'permissions/update' => 'permissions#update', :via => :post, :as => :permissions_update
  match 'permissions/delete' => 'permissions#destroy', :via => :post, :as => :permissions_delete
  match 'permissions/sort' => 'permissions#sort', :via => :post, :as => :permissions_sort

  get "channel/index"
  post "channel/notice"
  post "channel/chat"
  post "channel/add_chat_schedule"
  post "channel/remove_chat_schedule"

  get "sms/index"

  get "events_zhaoxian/index"
  get "events_zhaoxian/list"
  get "events_zhaoxian/new"
  get "events_zhaoxian/edit"
  post 'events_zhaoxian/create_zhaoxian'
  post 'events_zhaoxian/update'
  match "events_zhaoxian/delete" => 'events_zhaoxian#delete_zhaoxian', :via => :post
  post "events_zhaoxian/delete_zhaoxian"
  match 'events_zhaoxian/copy/:zone/:id/' => 'events_zhaoxian#copy', :via => :post
  match 'events_zhaoxian/:zone/copy_list' => 'events_zhaoxian#copy_list', :via => :post

  get "events_campaign_exp/index"
  get "events_campaign_exp/list"
  get "events_campaign_exp/new"
  get "events_campaign_exp/edit"
  post 'events_campaign_exp/create_campaign_exp'
  post 'events_campaign_exp/update'
  match "events_campaign_exp/delete" => 'events_campaign_exp#delete_campaign_exp', :via => :post
  post "events_campaign_exp/delete_campaign_exp"
  match 'events_campaign_exp/copy/:zone/:id/' => 'events_campaign_exp#copy', :via => :post
  match 'events_campaign_exp/:zone/copy_list' => 'events_campaign_exp#copy_list', :via => :post

  get "events_zonemarket/index"
  get "events_zonemarket/list"
  get "events_zonemarket/new"
  get "events_zonemarket/edit"
  post 'events_zonemarket/create_zonemarket'
  post 'events_zonemarket/update'
  match "events_zonemarket/delete" => 'events_zonemarket#delete_zonemarket', :via => :post
  post "events_zonemarket/delete_zonemarket"
  match 'events_zonemarket/copy/:zone/:id/' => 'events_zonemarket#copy', :via => :post
  match 'events_zonemarket/:zone/copy_list' => 'events_zonemarket#copy_list', :via => :post

  get "events_soul/index"
  get 'events_soul/list'

app/gm/app/controllers/events_zonemarket_controller.rb
# events_controller.rb

class EventsZonemarketController < EventsController
  #layout 'main'
  layout 'events'

  protect_from_forgery

  before_filter :require_user

  access_control do
    allow :admin, :p0, :p1
  end

  set_tab :zone_market

  include Eventable
  gen_controller_event :zonemarket


  def list
    @active = "zonemarket_link"
    @zone = params[:zone] || 1
    @list = proxy.get_zonemarket_events(@zone)
    @list.each {|n| parse_time(n, n) }
  end

  def new
    zone = params[:zone]
    @zonemarket = {'zone' => zone}
  end

  def edit
    @id = params[:id]
    @zone = params[:zone]
    @zonemarket = proxy.get_zonemarket_event(@id)
    parse_time(@zonemarket, @zonemarket)
  end

  def create_zonemarket
    data = params[:zonemarket]
    zone = params[:zone]
    parse_time(data, data)
    res, data = proxy.create_zonemarket_event(data.zone, data, cur_user)
    if res['success']
      redirect_to :action => 'edit', :zone => zone, :id => data.id
    else
      render :json => res
    end
  end

  def delete_zonemarket
    user = cur_user
    zone = params[:zone].to_i
    id = params[:id].to_i
    res = proxy.delete_zonemarket_event(id, user)
    if res['success']
      current_user.site_user_records.create(
        :action => 'delete_event',
        :success => true,
        :zone => zone,
        :param1 => 'zonemarket',
        :param2 => id,
      )
      redirect_to :action => 'list', :zone => zone
    else
      render :json => res
    end
  end

  def update
    user = cur_user
    data = params[:zonemarket]
    zone = params[:zone]
    parse_time(data, data)

    res = proxy.save_zonemarket_event(zone, data, user)
    if res['success']
      redirect_to :action => 'edit', :zone => zone, :id => data.id
    else
      render :json => res
    end
  end

end

app/gm/app/views/events_zonemarket/_form.html.erb
<%= render 'shared/events_top' %>
<div>
  <%= render 'shared/items_top' %>
  <div>
    <div id="zonemarket">
      <h2><%=t :zonemarket_event%></h2>
      <div id="zonemarket_hint" style="display:none;width:100%;padding:2px 4px 2px 4px;">
        <span id="zonemarket_hint_content" style="color:white;"></span>
      </div>
      <table class='gridtable table table-striped table-bordered'>
        <col width="20px" />
        <col width="30px" />
        <col width="20px" />
        <col width="20px" />
        <tr>
          <th><%=t :id%></th>
          <th><%=t :zone%></th>
          <th><%=t :start_time%></th>
          <th><%=t :end_time%></th>
        </tr>
        <tr>
          <td><%= form.text_field :id,  :readonly => true, :size => 3 %></td>
          <td><%= form.text_field :zone,  :readonly => true, :size => 3 %></td>
          <td><%= form.text_field :startTime, :size => 15 %></td>
          <td><%= form.text_field :endTime, :size => 15 %></td>
        </tr>
      </table>
      <%= render 'shared/events_downandup' %>
    </div>
  </div>
</div>
<script type="text/javascript">
  function getTable(){
    var data = new Object();
    data.zonemarket_startTime = $('#zonemarket_startTime').val();
    data.zonemarket_endTime = $('#zonemarket_endTime').val();
    data.zonemarket_maxNum = $('#zonemarket_maxNum').val();
    return data;
  }

  function toText(){
    $('#json').val(JSON.stringify(getTable(), null));
  }

  function toDisplay(){
    var data = JSON.parse($('#json').val())
    for(var name in data){
      if(typeof(data[name]) == 'function'){
        //
      }else{
        if($('#'.concat(name)).attr('type') == 'checkbox'){
          $('#'.concat(name)).prop('checked', data[name]);
        }else{
          $('#'.concat(name)).val(data[name]);
        }
      }
    }
  }

  $('#zonemarket_startTime').datetimepicker();
  $('#zonemarket_endTime').datetimepicker();

  $(document).ready(initDataSource());
</script>

app/gm/app/views/events_zonemarket/edit.html.erb
<h1><%=t :edit_zonemarket %></h1>
<%= form_for_hash @zonemarket, 'zonemarket', {:action => "update"}, :method => :post, :class => "form" do |f| %>
  <%= render :partial => "form", :object => f, :locals => { :zonemarket => @zonemarket } %>
  <%= f.submit t(:save), :class => "btn btn-info" %>
<% end %>
<br />
<%= link_to t(:zonemarket_list_url), {:action => "list", :zone => @zone}, :class => "btn btn-warning" %>

app/gm/app/views/events_zonemarket/index.html.erb
<%= render 'shared/grant' %>
<%= render 'shared/events_top' %>

<div id="zonemarket">
  <h3><span class="label label-default"><%=t :zone_market %></span></h3>
  <form id="data_form" action="/events_zonemarket/1" method="POST" class="form">
    <div class="row">
      <div class="col-md-2">
        <span>开启: </span>
        <%= check_box_tag 'zonemarket_enabled' %>
      </div>
      <div class="col-md-4">
        <div class="input-group">
          <span class="input-group-addon"><%= t :start_time %></span>
          <%= text_field_tag :start_time_zm, nil, :class => "form-control" %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="input-group">
          <span class="input-group-addon"><%= t :end_time %></span>
          <%= text_field_tag :end_time_zm, nil, :class => "form-control" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="input-group">
          <span class="input-group-addon"><%= t :status %></span>
          <%= text_field_tag :grant_status_zm, nil, :readonly => true, :class => "form-control" %>
        </div>
      </div>
    </div>

    <%= render 'shared/events_downandup' %>
    <input class="btn btn-info" type="button" onclick="updateZoneMarket()" value="<%= t :save %>"></input>
  </form>

  <br/>

  <form id="zonemarketCopyForm" action="/events_zonemarket/1/copy" method="POST">
    <div class="alert alert-success">
      <%=t :copy_current_config_to_zone%>,
      <%=t :confirm_your_config_saved%>,
      <%=t :enter_zone_split_with_space_like%>2 3 6
    </div>

    <%= text_field_tag "zonemarket_copy_zones", nil, :size => 100, :placeholder => "2 3 6", :class => "form-control" %>
    <input class="btn btn-success" type="button" onclick="copyZone('/events_zonemarket/','zonemarket_copy_zones')" value="<%=t :copy_current_config_to_zone%>">
  </form>
</div>


<script type="text/javascript">

  /////////////////////////////////////////////
  // common
  //

  $("#zone").change(onZoneChange);
  onZoneChange(); // load event configs at zone 1

  function onZoneChange()
  {
    var zoneIndex = $("#zone").val();
    console.log("zone=" + zoneIndex);

    $('#data_form').attr('action', '/events_zonemarket/' + zoneIndex);

    $('#zonemarket').mask('读取中...');

    getZoneMarket(zoneIndex, function(data)
    {
      $('#zonemarket').unmask()
      if(data['data'])
      {
        $("#zonemarket_enabled").prop('checked', data['data']['enabled']);
        $('#start_time_zm').val(data['data']['startTime']);
        $('#end_time_zm').val(data['data']['endTime']);
        var statusStr = getGrantStatusStr(data['data']['grantStatus'])
        $('#grant_status_zm').val(statusStr)
      }
      else
      {
        $("#zonemarket_enabled").prop('checked', false);
        $('#start_time_zm').val("");
        $('#end_time_zm').val("");
      }
      //
    });
  }

  function getTable(){
    var data = new Object();
    data.zonemarket_enabled = $('#zonemarket_enabled').prop('checked');
    data.start_time_zm = $('#start_time_zm').val();
    data.end_time_zm = $('#end_time_zm').val();
    return data;
  }


  ////////////////////////////////////////////////////////
  //
  //////////////////////////////////////////////////////////

  ajaxSubmit($('#zonemarketCopyForm'));
  $('#start_time_zm').datetimepicker();
  $('#end_time_zm').datetimepicker();


  function getZoneMarket(zoneIndex, callback)
  {
    $.ajax({
      type: 'GET',
      url: '/events_zonemarket/' + zoneIndex
    }).done(function(jsonData){
      // console.log(jsonData);
      if (callback) {
        callback(jsonData);
      }
    }).fail(function(xhr, status){
      showStatus('Something wrong!', 'fail');
    });
  }

  function updateZoneMarket()
  {
    $.ajax({
      type: 'POST',
      url: '/events_zonemarket/' +  $("#zone").val(),
      data: {
              "enabled":$("#zonemarket_enabled").prop('checked'),
              "startTime":$("#start_time_zm").val(),
              "endTime":$('#end_time_zm').val(),
            }
    }).done(function(json){
      // console.log(jsonData);
       if(json && json['success'])
       {
         showStatus('save success~', 'green')
       }
       else if(json)
       {
         //showStatus('copy error, reason: ' + json['reason'], 'red')
         showStatus(parseError(json), 'red')
       }
       else
       {
         showStatus('save error', 'red')
       }
      }).fail(function(xhr, status){
      showStatus('Something wrong!', 'fail');
    });
  }

</script>

app/gm/app/views/events_zonemarket/list.html.erb
<%= render 'shared/grant' %>
<h3><span class="label label-default"><%=t :choose_zone%></span></h3>
<%= render 'shared/zones' %>
<br/>
<a href="#" onclick="toCreate()" class="btn btn-info"><%=t :create_zonemarket_event%></a>
<br/><br/>
<table id='eventstable' class='table table-striped table-bordered table-hover'>
  <tr>
    <th><%=t :id %></th>
    <th><%=t :zone %></th>
    <th><%=t :open_date%></th>
    <th><%=t :close_date%></th>
    <th><%=t :actions %></th>
  </tr>
  <% @list.each do |n| %>
  <tr>
    <td><%=n.id%></td>
    <td><%=n.zone%></td>
    <td><%=n.startTime%></td>
    <td><%=n.endTime%></td>
    <td>
      <%= link_to(:edit, {:action => :edit, :id => n.id, :zone => n.zone}, {:method => :get}) %>
      <%= link_to(:delete, {:action => :delete_zonemarket, :id => n.id, :zone => n.zone}, {:method => :post, :data => {:confirm => t(:are_you_sure_to_delete)}}) %>
    </td>
  </tr>
  <% end %>

</table>
<form id="copyForm" action="'events_zonemarket/copy_zonemarket/1/copy_list'" method="POST" class="form">
  <div class="alert alert-success">
    <%=t :copy_current_config_to_zone%>,
    <%=t :confirm_your_config_saved%>,
    <%=t :enter_zone_split_with_space_like%>2 3 6
  </div>
  <%= text_field_tag "copy_zones", nil, :size => 100, :placeholder => "2 3 6", :class => "form-control" %>
  <br/>
  <span><%=t :force_copy%></span>
  <%= check_box_tag 'enable_force_copy' %>
  <input type="button" onclick="copy()" value="<%=t :copy_current_config_to_zone%>" class="btn btn-success">
</form>
<script type="text/javascript">
  /////////////////////////////////////////////
  // common
  //

  $("#zone").change(onZoneChange);

  function onZoneChange()
  {
    var zoneIndex = $("#zone").val();
    console.log("zone=" + zoneIndex);
    getEvents(zoneIndex);
  }

  function getEvents(zone) {
    var zoneIndex = $("#zone").val();
    window.location.href = "/events_zonemarket/list?zone=" + zoneIndex;
  }

  function toCreate(){
    var zoneIndex = $("#zone").val();
    window.location.href = "/events_zonemarket/new?zone=" + zoneIndex;
  }

  function copy()
  {
    if($("#enable_force_copy").prop('checked'))
    {
      if(confirm("<%=t :force_copy_tips%>"))
      {
        copyzonemarketEvents();
      }
      else
      {
        //
      }
    }
    else
    {
      copyzonemarketEvents();
    }
  }

  function copyzonemarketEvents()
  {
    var zoneIndex = $("#zone").val();
    $.ajax({
      type: 'POST',
      url: '/events_zonemarket/' + zoneIndex + "/copy_list",
      data: {
              "tozones":$("#copy_zones").val(),
              "force_copy":$("#enable_force_copy").prop('checked')
            }
    }).done(function(json){
      if(json && json['success'])
      {
        showStatus('copys success~', 'green')
      }
      else if(json)
      {
        //showStatus('copys error, reason: ' + json['reason'], 'red')
        showStatus(parseError(json), 'red')
      }
      else
      {
        showStatus('copys error', 'red')
      }
      }).fail(function(xhr, status){
      showStatus('Something wrong!', 'red');
    });
  }

  function deleteCur(zone, id)
  {
    if(confirm("<%=t :confirm_operation%>"))
    {
      deletezonemarketEvent(zone, id);
    }
    else
    {
      //
    }
  }

  function deletezonemarketEvent(zone, id)
  {
    $.ajax({
      type: 'POST',
      url: '/events_zonemarket/delete/' + zone + "/" + id
    }).done(function(json){
      if(json && json['success'])
      {
        showStatus('delete success~', 'green')
        onZoneChange()
      }
      else
      {
        showStatus('delete error', 'red')
      }
      }).fail(function(xhr, status){
      showStatus('Something wrong!', 'red');
    });
  }
</script>

app/gm/app/views/events_zonemarket/new.html.erb
<h1><%=t :edit_zonemarket %></h1>
<%= form_for_hash @zonemarket, 'zonemarket', {:action => "create_zonemarket"}, :method => :post, :class => "form" do |f| %>
  <%= render :partial => "form", :object => f, :locals => { :zonemarket => @zonemarket } %>
  <%= f.submit t(:save), :class => "btn btn-info" %>
<% end %>
<br />
<%= link_to t(:zonemarket_list_url), events_zonemarket_list_url, :class => "btn btn-warning" %>