app/gm/config/routes.rb
Gm::Application.routes.draw do

  get "limit_event/list"
  get "limit_event/edit"
  get "limit_event/new"
  get "limit_event/delete"
  post "limit_event/create"
  post "limit_event/update"

  get "normal_event/list"
  get "normal_event/edit"
  get "normal_event/new"
  get "normal_event/delete"
  post "normal_event/create"
  post "normal_event/update"

  get "events_campaign_exp/list"

  get "cdkeys/index"
  get "cdkeys/search"
  get "cdkeys/manage"
  post "cdkeys/generate"
  post "cdkeys/process_redeemed_cdkeys"
  post "cdkeys/import_from_local"
  post "cdkeys/import"
  post "cdkeys/export_all"

  get "cdkey/index"

  root :to => "application#index"

  match "i18n" => 'application#i18n', :via => :put
  match "logout" => 'user_sessions#destroy', :via => :get

  post 'api/client_version'
  post 'api/maintainance'
  post 'api/list_zones'
  post 'api/list_user_zones'
  post 'api/is_valid_cdkey'
  post 'api/use_cdkey'
  post 'api/list_user_zones'
  post "api/get_game_characters"
  post 'api/process_action_log'
  post 'api/process_redeemed_cdkeys'

  get 'site_users/list'
  match 'site_users/:id/update_super' => 'site_users#update_super', :via => :put
  match 'site_users/:id/update_role' => 'site_users#update_role', :via => :put
  match 'site_users/:id/update_active' => 'site_users#update_active', :via => :put
  match 'site_users/:id/reset_failed_login_count' => 'site_users#reset_failed_login_count', :via => :post
  match 'site_users/:id/edit_role' => 'site_users#edit_role', :via => :get, :as => :edit_site_user_role
  match 'site_users/:id/edit_active' => 'site_users#edit_active', :via => :get, :as => :edit_site_user_active
  match 'site_users/:id/edit_super(.:format)' => 'site_users#edit_super', :via => :get, :as => :edit_site_user_super
  match 'site_users/:id/deliver_verification_instructions' => 'site_users#deliver_verification_instructions', :via => :post, :as => :deliver_verification_instructions
  match 'site_users/:id/skip_verification' => 'site_users#skip_verification', :via => :post, :as => :skip_verification
  match 'site_user_verification/:token' => 'site_user_verification#show', :via => :get, :as => :site_user_verification
  get 'site_user_records/index'
  get 'site_user_records/search'

  get 'notif_alerts/list', :as => :list_notif_alerts
  post 'notif_alerts/check_all' => 'notif_alerts#check_all', :as => :check_notif_alert_all
  match 'notif_alerts/:id/edit' => 'notif_alerts#edit', :via => :get, :as => :edit_notif_alert
  post 'notif_alerts/:id/check' => 'notif_alerts#check', :as => :check_notif_alert

  get 'notif_receivers/list', :as => :list_notif_receivers
  match 'notif_receivers/:id/edit' => 'notif_receivers#edit', :via => :get, :as => :edit_notif_receiver

  match 'grant_records/grant'  => 'grant_records#grant', :via => :post
  match 'grant_records/reject' => 'grant_records#reject', :via => :post
  match 'grant_records/old_requests' => 'grant_records#old_requests', :via => :get
  resources :grant_records

  get 'wldh/list'
  match 'wldh/:id/stages/:stage' => 'wldh#show_stages', :via => :get, :as => :stages_wldh
  match 'wldh/:id/stages/:stage/:zone/:player_id' => 'wldh#show_stages_player', :via => :get, :as => :stages_player_wldh
  match 'wldh/:id/stages/:stage/fights/:mode/:fight_id' => 'wldh#show_stages_fight', :via => :get, :as => :stages_fight_wldh
  match 'wldh/:id/activate' => 'wldh#activate', :via => :post, :as => :activate_wldh
  match 'wldh/:id/boost' => 'wldh#boost', :via => :post, :as => :boost_wldh
  match 'wldh/:id/enroll' => 'wldh#enroll', :via => :post, :as => :enroll_wldh
  match 'wldh/:id/reset_stages' => 'wldh#reset_stages', :via => :post, :as => :reset_wldh_stages
  match 'wldh/grant/:id/:grant' => 'wldh#grant', :via => :post, :as => :grant_wldh
  match 'wldh/viewWulinRanks' => 'wldh#viewWulinRanks', :via => :get

  get 'data_query/index'
  post 'data_query/cache'
  post 'data_query/debug'
  post 'data_query/submit'
  match 'data_query/log/:id' => 'data_query#showlog', :via => :get
  match 'data_query/log/:id' => 'data_query#deletelog', :via => :delete

  match 'cdkey/queryKey/:key' => 'cdkey#queryKey', :via => :get

  resources :user_sessions
  resources :site_users
  resources :site_user_records
  resources :notif_alerts
  resources :notif_receivers
  resources :wldh

  get 'client_version/index'
  get 'client_version/edit'
  post 'client_version/publish'

  get 'app_version/index'
  get 'app_version/edit'
  post 'app_version/publish'

  get 'zone/index'
  post 'zone/saveNumOpenZones'

  get 'maintainance/index'
  post 'maintainance/update'

  get 'gm_pay/index'
  post 'gm_pay/add'

  get 'server_settings/index'
  post 'server_settings/dev_mode'
  post 'server_settings/save'
  post 'server_settings/delete'
  post 'server_settings/reload_server_list'
  post 'server_settings/garbage_collect_all'

  get 'zone_settings/index'
  post 'zone_settings/save'
  post 'zone_settings/open_zone_auto_set'
  post 'zone_settings/restore_default_settings'
  post 'zone_settings/delete'

  get 'queuing_settings/index'
  post 'queuing_settings/save'
  post 'queuing_settings/delete'

  get "bills/index"
  get "bills/search"
  get 'bills/total'
  get 'bills/low_search'

  get 'data/view'
  get 'data/player'
  get 'data/give'
  get "/data/query_guild"
  post "/data/guild_search"
  
  get 'editdata/edit'

  match 'actionlog' => 'data#actionlog', :via => :get
  match 'actionlogSpecial' => 'data#actionlogSpecial', :via => :get

  get "wushuplayer/raw"
  get "wushuplayer/load"

  get "action_logs/index"
  get "action_logs/search"
  get "action_logs/manage"
  post "action_logs/delete_old"
  post "action_logs/process_remain_logs"

  get "elastic_action_log/index"
  get "elastic_action_log/search"

  get "anti_cheat/index"
  get "anti_cheat/search_cheater", :as => :search_cheater
  post "anti_cheat/add_cheater", :as => :add_cheater
  post "anti_cheat/del_cheater", :as => :del_cheater
  post "anti_cheat/clear_cheaters", :as => :clear_cheaters
  get "anti_cheat/search_monitor", :as => :search_monitor
  post "anti_cheat/add_monitor", :as => :add_monitor
  post "anti_cheat/del_monitor", :as => :del_monitor
  post "anti_cheat/clear_monitors", :as => :clear_monitors

  match 'archive/:zone/:id' => 'archive#find', :via => :get, :as => :archive_find
  match 'archive/:zone/:id/:time' => 'archive#load', :via => :get, :as => :archive_view
  match 'archive/:zone/:id/:time/delete' => 'archive#delete', :via => :post, :as => :archive_delete

  get 'config/complete/:type' => 'config#complete'

  match 'archive/:zone/:id' => 'archive#find', :via => :get, :as => :archive_find
  match 'archive/:zone/:id/:time' => 'archive#load', :via => :get, :as => :archive_view
  match 'archive/:zone/:id/:time/delete' => 'archive#delete', :via => :post, :as => :archive_delete

  get 'data/view'
  get 'data/history'
  get 'data/raw'
  get 'data/give'
  get 'data_batch/edit'
  post 'data_batch/save'
  post 'data_batch/batch_save'

  match 'data/:zone/:id' => 'data#load', :via => :get
  match 'data/:zone/:id/json' => 'data#export', :via => :get
  match 'data/:zone/:id/json' => 'data#import', :via => :put
  match 'data/:zone/:id' => 'data#save', :via => :put
  match 'data/:zone/:id' => 'data#delete', :via => :delete

  post "player/set_permission"
  post "player/permission_list"
  post "player/get_permission"
  post "player/get_block_detail"
  post "player/unlock_block"
  post "player/set_player_permission"
  get "player/index"
  match "player/:zone/:name" => 'player#byName', :via => :get
  match "player/kick/:zone/:id" => 'player#kick', :via => :post

  get "user/index"
  post "user/query"
  post "user/query_player"
  match "user/by_email" => 'guser#by_email', :via => :get
  match "user/:id" => 'guser#by_id', :via => :get

  match 'permissions' => 'permissions#show', :via => :get
  match 'permissions/create' => 'permissions#create', :via => :post, :as => :permissions_create
  match 'permissions/update' => 'permissions#update', :via => :post, :as => :permissions_update
  match 'permissions/delete' => 'permissions#destroy', :via => :post, :as => :permissions_delete
  match 'permissions/sort' => 'permissions#sort', :via => :post, :as => :permissions_sort

  get "channel/index"
  post "channel/notice"
  post "channel/chat"
  post "channel/add_chat_schedule"
  post "channel/remove_chat_schedule"

  get "sms/index"

  get "events_zhaoxian/index"
  get "events_zhaoxian/list"
  get "events_zhaoxian/new"
  get "events_zhaoxian/edit"
  post 'events_zhaoxian/create_zhaoxian'
  post 'events_zhaoxian/update'
  match "events_zhaoxian/delete" => 'events_zhaoxian#delete_zhaoxian', :via => :post
  post "events_zhaoxian/delete_zhaoxian"
  match 'events_zhaoxian/copy/:zone/:id/' => 'events_zhaoxian#copy', :via => :post
  match 'events_zhaoxian/:zone/copy_list' => 'events_zhaoxian#copy_list', :via => :post

  get "events_campaign_exp/index"
  get "events_campaign_exp/list"
  get "events_campaign_exp/new"
  get "events_campaign_exp/edit"
  post 'events_campaign_exp/create_campaign_exp'
  post 'events_campaign_exp/update'
  match "events_campaign_exp/delete" => 'events_campaign_exp#delete_campaign_exp', :via => :post
  post "events_campaign_exp/delete_campaign_exp"
  match 'events_campaign_exp/copy/:zone/:id/' => 'events_campaign_exp#copy', :via => :post
  match 'events_campaign_exp/:zone/copy_list' => 'events_campaign_exp#copy_list', :via => :post

  get "events_zonemarket/index"
  get "events_zonemarket/list"
  get "events_zonemarket/new"
  get "events_zonemarket/edit"
  post 'events_zonemarket/create_zonemarket'
  post 'events_zonemarket/update'
  match "events_zonemarket/delete" => 'events_zonemarket#delete_zonemarket', :via => :post
  post "events_zonemarket/delete_zonemarket"
  match 'events_zonemarket/copy/:zone/:id/' => 'events_zonemarket#copy', :via => :post
  match 'events_zonemarket/:zone/copy_list' => 'events_zonemarket#copy_list', :via => :post

  get "events_soul/index"
  get 'events_soul/list'

app/gm/app/helpers/wldh_helper.rb
module WldhHelper
end

app/gm/app/views/wldh/_form.html.erb
<%= render "shared/error_messages", :target => @wulin %>

<div class="row">
  <div class="col-md-4">
    <div class="input-group">
      <span class="input-group-addon"><%= t(:start_time) %></span>
      <%= form.text_field :start_time, :class => "form-control" %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="input-group">
      <span class="input-group-addon"><%= t(:max_players) %></span>
      <%= form.number_field :maxPlayers, :class => "form-control" %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="input-group">
      <span class="input-group-addon"><%= t(:min_players) %></span>
      <%= form.text_field :minPlayers, :class => "form-control" %>
    </div>
  </div>
</div>

<br/>

<div class="row">
  <div class="col-md-2">
    <div class="input-group">
      <span class="input-group-addon"><%= t(:division) %></span>
      <%= form.number_field :division, :class => "form-control" %>
    </div>
  </div>
  <div class="col-md-2">
    <div class="input-group">
      <span class="input-group-addon"><%= t(:counter) %></span>
      <%= form.number_field :counter, :class => "form-control" %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="input-group">
      <span class="input-group-addon"><%= t(:baseTid) %></span>
      <%  baseConfigs = {}
          CocsProxy.instance.getGameConfig('wulin').each do |k,v|
            baseConfigs[v.name] = k
          end
      %>
      <%= select("wulin_model", "baseTid", options_for_select(baseConfigs, @wulin.baseTid), {}, :class => "form-control") %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="input-group">
      <span class="input-group-addon"><%= t(:rewardTid) %></span>
      <%  rewardConfigs = {}
          CocsProxy.instance.getGameConfig('wulinRewards').each do |k,v|
            rewardConfigs[v.name] = k
          end
      %>
      <%= select("wulin_model", "rewardTid", options_for_select(rewardConfigs, @wulin.rewardTid), {}, :class => "form-control") %>
    </div>
  </div>
</div>

<br/>

<!-- 选区 -->
<%= form.label t(:zones), :class => "label label-success" %>
<%  allZones = {}
    proxy = CocsProxy.instance
    proxy.getGameConfig('zones').each_with_index do |z, i|
      onlineNum = proxy.numOnline(i + 1)
      value     = proxy.getArenaRankTotalValue(i + 1, 0, 14)
      key = sprintf("%03d 区 %s 在线人数:%06d 战斗力:%010d", i+1, z['name'], onlineNum, value)
      allZones[key] = i + 1
    end

    selectedZones = []
	CocsProxy.instance.getAllWulins.each do |w|
		if w.is_active? and w.id != @wulin.id
		  w.zones.each {|z| selectedZones << z }
		end
	end
%>
&nbsp;&nbsp;&nbsp;&nbsp;<span class="label label-default"><%= t(:used_zones) %><%= selectedZones %></span>
<br/><br/>
<%= select("wulin_model", "zones", options_for_select(allZones, @wulin.zones), {}, {:multiple => true, :size => 10, :class => "form-control"}) %>

<br/>

<script type='text/javascript'>
  $('#wulin_model_start_time').datetimepicker();
</script>

app/gm/app/views/wldh/edit.html.erb
<h1><%=t :edit_wulin %></h1>

<%= form_for @wulin, :url => { :action => "update"}, :method => :put, :class => "form" do |f| %>
  <%= render :partial => "form", :object => f, :locals => { :wulin => @wulin } %>
  <%= f.submit t(:save), :class => "btn btn-info" %>
<% end %>

<br />
<%= link_to t(:view_wulin), wldh_url(@wulin.id), :class => "btn btn-warning" %>

app/gm/app/views/wldh/list.html.erb
<%= link_to t(:create_wulin), new_wldh_url, :class => "btn btn-info" %>
<%= link_to t(:view_wulin_ranks), {:action => "viewWulinRanks"}, :class => "btn btn-warning" %>

<br/><br/>

<table class="table table-striped table-bordered table-hover">

  <tr>
    <th><%=t :id %></th>
    <th><%=t :counter %></th>
    <th><%=t :division %></th>
    <th><%=t :start_time %></th>
    <th><%=t :max_players %></th>
    <th><%=t :min_players %></th>
    <th><%=t :stage %></th>
    <th><%=t :running %></th>
    <th><%=t :baseTid %></th>
    <th><%=t :rewardTid %></th>
    <th><%=t :zones %></th>
    <th><%=t :status %></th>
    <th><%=t :grant_status %></th>
    <th><%=t :num_enroll %></th>
    <th><%=t :actions %></th>
    <th><%=t :grant_actions %></th>
  </tr>

  <% if @page and @page.data %>
    <% @page.data.each_with_index do |wulin, i| %>
      <tr id='<%= wulin.id %>'>
        <td><%= link_to wulin.id, wldh_url(wulin.id) %></td>
        <td><%= wulin.counter %></td>
        <td><%= wulin.division %></td>
        <td><%= wulin.start_time %></td>
        <td><%= wulin.maxPlayers %></td>
        <td><%= wulin.minPlayers %></td>
        <td><%= wulin.stage_name %></td>
        <td><%= wulin.running %></td>
        <td><%= wulin.baseConfig.name if wulin.baseConfig %></td>
        <td><%= wulin.rewardConfig.name if wulin.rewardConfig %></td>
        <td><%= wulin.zones.collect {|z| z } if wulin.zones %></td>
        <td><%= if wulin.is_history? then t(:closed) elsif wulin.is_active? then t(:activated) else t(:stage_not_activated) end %></td>
        <td>
          <% if wulin.grantStatus.nil? %>
            <%=t :granted%>
          <% elsif wulin.grantStatus == 0 %>
            <%=t :need_grant%>
          <% elsif wulin.grantStatus == 1 %>
            <%=t :granted%>
          <% elsif wulin.grantStatus == 2 %>
            <%=t :rejected%>
          <% else %>
            <%=t :unknown%>
          <% end %>
        </td>
        <td><%= wulin.num_enroll(:newbie) %>, <%= wulin.num_enroll(:master) %></td>
        <td>
          <% if wulin.stageSymbol == :enroll %>
            <% if wulin.is_enrolling? %>
            <%=t :is_enrolling %>
            <% else %>
            <div>
              <form id="enroll" action="<%= enroll_wldh_url(wulin.id) %>" method="post">
                <span><%=t :enroll_num %>: </span>
                <input type="number" name="num" value="1000"/>
                <input type="submit" value="<%=t :auto_enroll %>" />
              </form>
            </div>
            <% end %>
          <% end %>

          <%= link_to t(:boost_to_next_stage), boost_wldh_url(wulin.id), 
              :confirm => t(:boost_to_next_stage_confirm), :method => :post %>
          <%= link_to t(:edit), edit_wldh_url(wulin.id) %>
          <%= link_to t(:delete),
            { :action => 'destroy', :id => wulin.id },
            { :confirm => t(:confirm_sure), :method => :delete } %>
          <%= link_to t(:reset_all_stages), reset_wldh_stages_url(wulin.id), 
              :confirm => t(:confirm_sure), :method => :post %>
        </td>
        <td>
          <% if @auth == 1 and wulin.grantStatus == 0 %>
            <%= link_to t(:accept), grant_wldh_url(wulin.id, 1), :method => :post %>
            <%= link_to t(:reject), grant_wldh_url(wulin.id, 2), :method => :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

<%= render 'shared/paging' %>

app/gm/app/views/wldh/new.html.erb
<h1><%= t(:create_wulin) %></h1>

<%= form_for @wulin, :url => { :action => "create" }, :class => "form" do |f| %>
<%= render :partial => "form", :object => f, :locals => { :wulin => @wulin } %>
<%= f.submit t(:create), :class => "btn btn-success" %>
<% end %>

<br/>

<div>
<%= link_to t(:list_wulin), wldh_list_url, :class => "btn btn-info" %>
</div>

app/gm/app/views/wldh/show.html.erb
<p>
<b><%=t :id %>:</b>
<%=h @wulin.id %>
</p>

<p>
<b><%=t :start_time %>:</b>
<%=h @wulin.start_time %>
</p>

<p>
<b><%=t :stage %>:</b>
<%=h @wulin.stage_name %>
</p>

<p>
<b><%=t :zones %>:</b>
<%=h @wulin.zones.collect {|z| z + 1} %>
</p>

<p>
<b><%=t :baseTid %>:</b>
<%=h @wulin.baseConfig.name %>
</p>

<p>
<b><%=t :rewardTid %>:</b>
<%=h @wulin.rewardConfig.name %>
</p>

<p>
<b><%=t :division %>:</b>
<%=h @wulin.division%>
</p>

<p>
<b><%=t :counter %>:</b>
<%=h @wulin.counter%>
</p>

<p>
<b><%=t :stages_wulin %>:</b>
<ol>
<% WulinModel::STAGES.each do |stage_sym| %>
  <li>
    <span><%= link_to t(stage_sym), stages_wldh_url(@wulin.id, stage_sym) %></span>
    <span><%=t :wulin_stage_duration %>: </span>
    <% startTime = @wulin.getStageTime(WulinModel.getStageIndex(stage_sym) - 1) %>
    <% endTime = @wulin.getStageTime(WulinModel.getStageIndex(stage_sym)) %>
    <% endTime = startTime if endTime == Float::INFINITY %>
    <span><%= TimeHelper.gen_date_time_sec(Time.at(startTime)) %></span>
    <span> - </span>
    <span><%= TimeHelper.gen_date_time_sec(Time.at(endTime)) %></span>
  </li>
<% end %>
</ol>
</p>

<p>
<b><%=t :final %>:</b>
<% @wulin.details.each do |name, detail| %>
<div>
<span><%= name %></span>
<span><%= detail.to_s %></span>
</div>
<% end %>
</p>



<div>
<%= link_to t(:edit_wulin), edit_wldh_url, :class => "btn btn-warning" %>
<%= link_to t(:list_wulin), wldh_list_url, :class => "btn btn-info" %>
</div>

app/gm/app/views/wldh/show_stages.html.erb
<a id='top'></a>

<p>
<b><%=t :id %>:</b>
<%=h @wulin.id %>
<b><%=t :stage %>:</b>
<%=h @stage %>
</p>

<a href='#newbie'><%=t :wulin_newbie %></a>
<a href='#master'><%=t :wulin_master %></a>

<% [ 'newbie', 'master' ].each do |mode| %>
<div>
  <h3><a id='<%= mode %>'><%=t "wulin_#{mode}" %></a></h3>
  <a href='#top'><%=t :back_to_top %></a>
  <a href="#<%= mode %>_rank_list"><%=t :wulin_rank_list %></a>
  <a href="#<%= mode %>_fight_list"><%=t :wulin_fight_list %></a>

  <% cai_info = WulinDb.getCaiInfo(@wulin.id, mode, @stage) %>
  <% fight_list = WulinDb.getStageFightList(@wulin.id, mode, @stage) %>

  <% if @stage.to_s.start_with?('taotai') %>
  <% rank_list = WulinDb.getTaotaiRankItemsByRange(@wulin.id, mode, @stage, 0, -1) %>
  <% elsif @stage.to_s.start_with?('xunhuan') %>
  <% rank_list = WulinDb.getXunhuanDynRankItemsByRange(@wulin.id, mode, 0, -1) %>
  <% else %>
  <% rank_list = nil %>
  <% end %>

  <% if cai_info %>
  <div>
    <h5><%=t :wulin_cai_info %></h5>
    <span><%= cai_info.to_s %></span>
  </div>
  <% end %>

  <% if rank_list %>
  <div>
    <h5><a id='<%= mode %>_rank_list'><%=t :wulin_rank_list %></a></h5>
    <ol>
    <% rank_list.each do |rank_info| %>
      <% p1 = "#{rank_info.playerId}:#{rank_info.playerZone}" %>
      <li>
        <span><%= rank_info.to_s %></span>
        <span> | </span>
        <span><%= link_to p1, stages_player_wldh_url(@wulin.id, @stage, rank_info.playerZone, rank_info.playerId) %></span>
      </li>
    <% end %>
    </ol>
  </div>
  <% end %>

  <% if fight_list %>
  <div>
    <h5><a id='<%= mode %>_fight_list'><%=t :wulin_fight_list %></a></h5>
    <ol>
      <% fight_list.each do |fight_info| %>
        <% p1 = "#{fight_info.playerId1}:#{fight_info.playerZone1}" %>
        <% p2 = "#{fight_info.playerId2}:#{fight_info.playerZone2}" %>
        <li>
          <span><%= fight_info.to_s %></span>
          <span> | </span>
          <span><%= link_to p1, stages_player_wldh_url(@wulin.id, @stage, fight_info.playerZone1, fight_info.playerId1) %></span>
          <span><%= link_to p2, stages_player_wldh_url(@wulin.id, @stage, fight_info.playerZone2, fight_info.playerId2) %></span>
        </li>
      <% end %>
    </ol>
  </div>
  <% end %>

<% end %>

<div>
<%= link_to t(:view_wulin), wldh_url, :class => "btn btn-info" %>
<%= link_to t(:list_wulin), wldh_list_url, :class => "btn btn-info" %>
</div>

app/gm/app/views/wldh/show_stages_fight.html.erb
<p>
<b><%=t :id %>:</b>
<%=h @id %>
<b><%=t :stage %>:</b>
<%=h @stage %>
<b><%=t :fight_id %></b>
<%=h @fight_id %>
</p>

<div>
  <span><%= @fight.to_s %></span>
<div>

<%= link_to t(@stage), stages_wldh_url(@id, @stage), :class => "btn btn-info" %>
</div>

app/gm/app/views/wldh/show_stages_player.html.erb
<a id='top'></a>

<p>
<b><%=t :id %>:</b>
<%=h @id %>
<b><%=t :stage %>:</b>
<%=h @stage %>
<b><%=t :player_id %></b>
<%=h @player_id %>
<b><%=t :zone %></b>
<%=h @zone %>
</p>

<%= link_to t(:data), "/data/view?zone=#{@zone}&id=#{@player_id}" %>
<a href='#newbie'><%=t :wulin_newbie %></a>
<a href='#master'><%=t :wulin_master %></a>

<% [ 'newbie', 'master' ].each do |mode| %>
<div>
  <h3><a id='<%= mode %>'><%=t "wulin_#{mode}" %></a></h3>
  <a href='#top'><%=t :back_to_top %></a>

  <% last_heima_fight = WulinDb.getLastHeimaFightInfo(@id, mode, @player_id, @zone) %>
  <% fight_list, num = WulinDb.getPlayerFightList(@id, mode, @player_id, @zone, WulinModel.getStageIndex(@stage) + 1) %>

  <% if last_heima_fight %>
  <div>
    <h5><%=t :wulin_last_heima_fight %></h5>
    <span><%= last_heima_fight.to_s %></span>
  </div>
  <% end %>

  <% if fight_list %>
  <div>
    <h5><%=t :wulin_fight_list %></h5>
    <ol>
      <% fight_list.each do |fight_info| %>
        <li>
          <span><%= fight_info.to_s %></span>
        </li>
      <% end %>
    </ol>
  </div>
  <% end %>

<% end %>

<div>
<%= link_to t(@stage), stages_wldh_url(@id, @stage), :class => "btn btn-info" %>
</div>